[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[[headers]]
for = "/"
[headers.values]
Access-Control_Allow_Origin="*"
Authorization="Bearer 54c8e5fa4d104f2f9ea178a688c8f6ea"
HTTP-status = "ok"